// app/layout.tsx
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google'; // Import Poppins font
import './globals.css';
import { Fragment } from 'react';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

// Initialize Poppins font
const poppins = Poppins({ weight: '400', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-gray-100 flex flex-col min-h-screen`}>
        <Navbar />
        <main className="flex-grow">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
